"""Tests for the v2 skill-adapter generator (#317 Phase 5).

Root `skills/` is canonical; `.agents/skills/` and `.claude/skills/` are generated
copies for runtimes that don't discover skills at the repo root. The properties
that matter: idempotency (regenerating twice is a no-op), staleness (a hand-edit to
a generated file is not authoritative and gets overwritten), provenance (only
SKILL.md gets a marker — a course-facing template must not), and deletion (a skill
removed from the canonical source disappears from every target).
"""
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent.parent / "tools"
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

import generate_adapters as ga  # noqa: E402


def _skill(root: Path, skill_id: str, skill_md: str, extra: dict[str, str] | None = None) -> None:
    d = root / "skills" / skill_id
    d.mkdir(parents=True)
    (d / "SKILL.md").write_text(skill_md, encoding="utf-8")
    for name, body in (extra or {}).items():
        (d / name).write_text(body, encoding="utf-8")


def test_desired_files_appends_marker_only_to_skill_md(tmp_path):
    _skill(tmp_path, "audit", "---\nname: audit\n---\nbody", {"TEMPLATE.md": "copy me verbatim"})
    desired = ga.desired_files(tmp_path / "skills")
    assert desired["audit/TEMPLATE.md"] == b"copy me verbatim"
    assert b"GENERATED by" in desired["audit/SKILL.md"]
    assert desired["audit/SKILL.md"].startswith(b"---\nname: audit\n---\nbody")


def test_resync_writes_new_target_from_scratch(tmp_path):
    _skill(tmp_path, "audit", "---\nname: audit\n---\nbody")
    desired = ga.desired_files(tmp_path / "skills")
    target = tmp_path / ".claude" / "skills"
    counts = ga.resync(target, desired, apply=True)
    assert counts == {"written": 1, "removed": 0, "unchanged": 0}
    assert (target / "audit" / "SKILL.md").is_file()


def test_regenerating_is_idempotent(tmp_path):
    _skill(tmp_path, "audit", "---\nname: audit\n---\nbody", {"T.md": "x"})
    desired = ga.desired_files(tmp_path / "skills")
    target = tmp_path / ".claude" / "skills"
    ga.resync(target, desired, apply=True)
    second = ga.resync(target, desired, apply=True)
    assert second == {"written": 0, "removed": 0, "unchanged": 2}


def test_a_hand_edit_to_a_generated_file_is_overwritten_not_preserved(tmp_path):
    """The generator, not a local edit, is authoritative for these paths — a
    hand-edit surviving regeneration would silently drift from the canonical
    source, the exact failure Phase 5 exists to prevent."""
    _skill(tmp_path, "audit", "---\nname: audit\n---\nbody")
    desired = ga.desired_files(tmp_path / "skills")
    target = tmp_path / ".claude" / "skills"
    ga.resync(target, desired, apply=True)
    (target / "audit" / "SKILL.md").write_text("TAMPERED", encoding="utf-8")
    counts = ga.resync(target, desired, apply=True)
    assert counts["written"] == 1
    assert "TAMPERED" not in (target / "audit" / "SKILL.md").read_text(encoding="utf-8")


def test_a_skill_removed_upstream_is_removed_from_the_target(tmp_path):
    _skill(tmp_path, "audit", "---\nname: audit\n---\nbody")
    _skill(tmp_path, "grading", "---\nname: grading\n---\nbody")
    target = tmp_path / ".claude" / "skills"
    ga.resync(target, ga.desired_files(tmp_path / "skills"), apply=True)
    assert (target / "grading").exists()

    # "grading" is removed from the canonical source (upstream deletion)
    import shutil
    shutil.rmtree(tmp_path / "skills" / "grading")
    counts = ga.resync(target, ga.desired_files(tmp_path / "skills"), apply=True)
    assert counts["removed"] == 1
    assert not (target / "grading").exists()
    assert (target / "audit").exists()          # untouched


def test_check_mode_never_writes(tmp_path):
    _skill(tmp_path, "audit", "---\nname: audit\n---\nbody")
    desired = ga.desired_files(tmp_path / "skills")
    target = tmp_path / ".claude" / "skills"
    counts = ga.resync(target, desired, apply=False)
    assert counts["written"] == 1
    assert not target.exists()


def test_this_repos_generated_adapters_are_up_to_date():
    """CI/pre-commit equivalent as a pytest: the committed .agents/skills/ and
    .claude/skills/ must already equal what the generator would produce — a stale
    adapter is exactly the drift this tool exists to prevent."""
    desired = ga.desired_files(ga.REPO_ROOT / "skills")
    for target in ga.TARGETS:
        counts = ga.resync(target, desired, apply=False)
        assert counts["written"] == 0 and counts["removed"] == 0, (
            f"{target} is stale: {counts}"
        )
