#!/usr/bin/env python3
"""Generate per-runtime skill-discovery adapters from the canonical `skills/` tree.

WHY THIS EXISTS (v2, #317 Phase 5)

  Root `skills/` is the canonical source (Agent Plugins 1.0 requires skills at the
  repo root). Codex and Claude Code do not discover skills there in a plain
  workspace — Codex needs `.agents/skills/`, Claude Code needs `.claude/skills/`
  (docs/architecture/adr-001-runtime-neutral-agent-packages.md, measured). Before
  this tool, `.claude/skills/` was a hand-maintained copy (Phase 3) — exactly the
  two-copies-drift risk Phase 2 already fixed once for FERPA patterns. This
  generates both adapters from one source instead.

WHAT IT DOES NOT DO

  It does not invent content. Every file under a generated skill directory is a
  byte-for-byte copy of the canonical file, except `SKILL.md`, which gets one
  trailing provenance comment appended (harmless to a renderer, informative to a
  human who opens the generated copy directly and wonders where to make an edit).
  A course-facing template a skill ships (e.g. `IMPROVEMENTS.template.md`) is
  copied unmarked — a marker on a file a course COPIES to create its own content
  would leak into that content.

IDEMPOTENCY AND STALENESS

  Regenerating is deterministic: given the same canonical `skills/`, every target
  is fully recomputed and resynced (files added, changed, or removed to match) —
  not diffed against its own prior output. A hand-edit to a generated file is
  silently overwritten on the next run; that is the point, not a bug — the
  generator, not a local edit, is authoritative for these paths.

Usage:
  uv run python lib/tools/generate_adapters.py          # write
  uv run python lib/tools/generate_adapters.py --check  # exit 1 if targets are stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SOURCE = REPO_ROOT / "skills"
TARGETS = (REPO_ROOT / ".agents" / "skills", REPO_ROOT / ".claude" / "skills")
GENERATOR = "lib/tools/generate_adapters.py"


def _marker(skill_id: str) -> str:
    return (
        f"\n<!-- GENERATED by {GENERATOR} from skills/{skill_id}/SKILL.md — "
        "do not edit this copy directly; edit the canonical file and regenerate. "
        "schema_version: 1 -->\n"
    )


def desired_files(source: Path) -> dict[str, bytes]:
    """{relative_path: content} for every file under every canonical skill
    directory, keyed like `<skill_id>/<name>` — the shape common to both targets."""
    out: dict[str, bytes] = {}
    for skill_dir in sorted(p for p in source.iterdir() if p.is_dir()):
        skill_id = skill_dir.name
        for path in sorted(skill_dir.rglob("*")):
            if not path.is_file():
                continue
            rel = f"{skill_id}/{path.relative_to(skill_dir).as_posix()}"
            content = path.read_bytes()
            if path.name == "SKILL.md":
                content += _marker(skill_id).encode("utf-8")
            out[rel] = content
    return out


def resync(target: Path, desired: dict[str, bytes], *, apply: bool) -> dict[str, int]:
    """Make `target` match `desired` exactly. Returns {written, removed, unchanged}."""
    counts = {"written": 0, "removed": 0, "unchanged": 0}
    existing: dict[str, bytes] = {}
    if target.is_dir():
        for path in sorted(target.rglob("*")):
            if path.is_file():
                existing[path.relative_to(target).as_posix()] = path.read_bytes()

    for rel, content in desired.items():
        if existing.get(rel) == content:
            counts["unchanged"] += 1
            continue
        counts["written"] += 1
        if apply:
            dst = target / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_bytes(content)

    for rel in existing:
        if rel not in desired:
            counts["removed"] += 1
            if apply:
                dst = target / rel
                if dst.is_file():
                    dst.unlink()
                    cur = dst.parent
                    while cur != target and cur.is_dir() and not any(cur.iterdir()):
                        cur.rmdir()
                        cur = cur.parent
    return counts


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--check", action="store_true", help="exit 1 if targets are stale")
    args = parser.parse_args(argv)

    source = args.repo_root / "skills"
    targets = (args.repo_root / ".agents" / "skills", args.repo_root / ".claude" / "skills")
    desired = desired_files(source)

    stale = False
    for target in targets:
        counts = resync(target, desired, apply=not args.check)
        rel = target.relative_to(args.repo_root)
        if args.check:
            if counts["written"] or counts["removed"]:
                stale = True
                print(f"{rel}: STALE ({counts['written']} to write, {counts['removed']} to remove)")
            else:
                print(f"{rel}: up to date ({counts['unchanged']} files)")
        else:
            print(f"{rel}: {counts['written']} written, {counts['removed']} removed, "
                  f"{counts['unchanged']} unchanged")

    if args.check and stale:
        print("adapters: STALE — run `uv run python lib/tools/generate_adapters.py`")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
