#!/usr/bin/env python3
"""Generate the agent-package registry and human-readable catalog from manifests.

Read-only inputs (agent-packages/*/manifest.yaml), deterministic outputs
(agent-packages/registry.yaml, agent-packages/CATALOG.md). Run after any manifest
change and commit the regenerated files — this is not a runtime dependency, it is
documentation generation, so CI checks the output is current rather than running
this on every request.

A meta/toolkit tool, not a package member (like cb_init, cb_update, cb_report_bug —
see AGENTS.md's meta/lifecycle carve-out): it describes all packages, so it cannot
belong to one.

Usage:
  uv run python lib/tools/package_catalog.py
  uv run python lib/tools/package_catalog.py --check   # exit 1 if output is stale
"""
from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
PACKAGE_GLOB = "agent-packages/*/manifest.yaml"
REGISTRY_PATH = REPO_ROOT / "agent-packages" / "registry.yaml"
CATALOG_PATH = REPO_ROOT / "agent-packages" / "CATALOG.md"

EFFECT_LABELS = {
    "read": "read",
    "local_write": "local write",
    "canvas_content_write": "Canvas content write",
    "canvas_grade_comment_write": "Canvas grade/comment write",
    "canvas_student_intervention": "Canvas per-student intervention",
}


def load_packages(repo_root: Path) -> list[dict]:
    packages = []
    for path in sorted(repo_root.glob(PACKAGE_GLOB)):
        packages.append(yaml.safe_load(path.read_text(encoding="utf-8")))
    return packages


def build_registry(packages: list[dict]) -> dict:
    return {
        "schema_version": 1,
        "generated_by": "lib/tools/package_catalog.py",
        "packages": [
            {
                "id": pkg["id"],
                "version": pkg["version"],
                "name": pkg["name"],
                "ships": pkg["ships"],
                "skills": [s["id"] for s in pkg["skills"]],
                "tool_count": len(pkg["tools"]),
            }
            for pkg in packages
        ],
    }


def render_catalog(packages: list[dict]) -> str:
    lines = [
        "# Canvas Toolbox Agent Package Catalog",
        "",
        "Generated by `lib/tools/package_catalog.py` from `agent-packages/*/manifest.yaml`. "
        "Do not hand-edit — regenerate after any manifest change.",
        "",
    ]
    for pkg in packages:
        lines.append(f"## {pkg['name']} (`{pkg['id']}`)")
        lines.append("")
        lines.append(pkg["description"])
        lines.append("")
        lines.append(f"- **Version:** {pkg['version']}")
        lines.append(f"- **Skills:** {', '.join(s['id'] for s in pkg['skills'])}")
        lines.append(f"- **Entry prompt:** `{pkg['entry_prompt']}`")
        lines.append(f"- **Data classes:** {', '.join(pkg['data_access']['classes'])}")
        lines.append(f"- **Credentials:** {', '.join(pkg['credentials']) or 'none'}")
        counts = Counter(t["effect"] for t in pkg["tools"])
        breakdown = ", ".join(
            f"{counts[e]} {EFFECT_LABELS[e]}" for e in EFFECT_LABELS if counts.get(e)
        )
        lines.append(f"- **Tools ({len(pkg['tools'])}):** {breakdown}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument(
        "--check", action="store_true", help="exit 1 if generated output is stale"
    )
    args = parser.parse_args(argv)

    packages = load_packages(args.repo_root)
    registry = build_registry(packages)
    registry_text = yaml.safe_dump(registry, sort_keys=False, default_flow_style=False, width=100)
    catalog_text = render_catalog(packages)

    registry_path = args.repo_root / "agent-packages" / "registry.yaml"
    catalog_path = args.repo_root / "agent-packages" / "CATALOG.md"

    if args.check:
        current_registry = registry_path.read_text(encoding="utf-8") if registry_path.is_file() else ""
        current_catalog = catalog_path.read_text(encoding="utf-8") if catalog_path.is_file() else ""
        if current_registry != registry_text or current_catalog != catalog_text:
            print("package catalog: STALE — run `uv run python lib/tools/package_catalog.py`")
            return 1
        print("package catalog: up to date")
        return 0

    registry_path.write_text(registry_text, encoding="utf-8")
    catalog_path.write_text(catalog_text, encoding="utf-8")
    print(f"wrote {registry_path} and {catalog_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
